syntax on              " enable syntax highlighting

set number             " show absolute line numbers
set relativenumber     " show relative line numbers
set numberwidth=4      " set width of line number column

set autoindent         " auto-indent new lines
set expandtab          " use spaces instead of tabs
set tabstop=2          " number of spaces per tab
set shiftwidth=2       " number of spaces for indentation

set ignorecase         " ignore case in search
set smartcase          " override ignorecase if search has uppercase

set confirm            " confirm before closing unsaved files

set laststatus=2       " always show status line

set clipboard=unnamed  " use unnamed register for system clipboard

