# symlink manager
brew "stow"
# Keyboard customiser
cask "karabiner-elements"

# Terminal emulator and multiplexer
cask "wezterm"
# Terminal multiplexer
brew "tmux"
# Plugin manager for tmux
brew "tpm"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line fuzzy finder written in Go
brew "fzf"
# Improved top (interactive process viewer)
brew "htop"
# Theme for zsh
brew "powerlevel10k"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"

# Optional
# Web browser
cask "google-chrome"
# Adaptive brightness for external displays
cask "lunar"
# Clipboard manager
cask "maccy"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Open-source code editor
cask "visual-studio-code"
