# symlink manager
brew "stow"

# Terminal
cask "wezterm"
cask "font-meslo-lg-nerd-font"
brew "powerlevel10k"
brew "tmux"
brew "tpm"
brew "tree"
brew "htop"
brew "fzf"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Version managers
brew "nvm"

# tools
cask "lunar"
cask "maccy"
cask "rectangle"
cask "visual-studio-code"
